#!/usr/bin/env bash

NICE=/bin/nice
NICENESS="${SSH_NICENESS:-10}"
SSHD=/usr/sbin/sshd
SSHD_OPTIONS="
 -D
 -e
 -u 0
"

while true; do
	sleep 0.1
	[[ -e /tmp/sshd-bootstrap.lock ]] || break
done

if [[ -f /setup.py ]]; then
  python /setup.py
else
  echo "not find setup.py"
fi

exec ${NICE} \
	-n ${NICENESS} \
	${SSHD} \
	${SSHD_OPTIONS}
